<?php
// Seitentitel
$this->headTitle()
    ->append("Wähle Dein Bild!");

$bgStyles = '';
foreach ($this->galeryFilesRel as $index => $galeryUrl) {
    $bgStyles .= "#bg-{$index} { background-image: url('{$galeryUrl}'); } ";
}
$this->headStyle()->appendStyle($bgStyles);

// JavaScript
$this->headScript()
    ->appendScript(
        "var imageUrls = {$this->galeryFilesJs};
        var selected = {$this->imageIndex};");
$this->headScript()
    ->appendFile("/js/auswahl.js");
?>


<?php // Hauptmenue ?>
<?php echo $this->partial('menu.phtml', array(
        'user' => $this->session->user,
        'isLoggedin' => $this->isLoggedin,
        'loginForm' => $this->loginForm,
        'newMemberForm' => $this->newMemberForm,
        'requestResetForm' => $this->requestResetForm,
        'updateMemberForm' => $this->updateMemberForm)); ?>

<?php // Hintergrundbilder ?>
<div id="bg-frame" class="sliding-frame">
    <?php foreach ($this->galeryFilesRel as $index => $galeryUrl) { ?>
        <div id="bg-<?php echo $index; ?>" class="sliding-card slided-<?php echo ($index == $this->imageIndex) ? 'center' : 'left'?>"></div>
    <?php } ?>
</div>

<?php // Hilfefenster ?>
<div class="absoluteWrapper" >
    <div id="helpBox" class="container transparentLight">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <button id="closeHelp" type="button" class="close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
        </div>
        <div id="helpContent" class="row">
            <div class="col-sm-12">
                <h1>Schritt 1 von 3</h1>
                <h2>Durchstöbere die Bilder</h2>
            </div>
            <div class="row">
                <div class="col-sm-3 col-sm-offset-2 col-md-2 col-md-offset-3">
                    <img src="/images/hilfe1-1.png"/ class="center-block">
                    <p>Mit den Pfeiltasten kannst du die Bilder durchstöbern.</p>
                </div>
                <div class="col-sm-2">
                    <span class="glyphicon glyphicon-chevron-right center-block"></span>
                </div>
                <div class="col-sm-3 col-md-2">
                    <img src="/images/hilfe1-2.png" class="center-block" />
                    <p>Mit dem Auslöser bestätigst du deine Auswahl.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="content">
    <form id="auswahl" action="ausschnitt" method="POST">
        <input type="hidden" id="image" name="image" value="" />
    </form>
</div>

<?php // Kontrollelement ?>
<?php echo $this->partial('cameraControl.phtml', array(
        'imageSelectable' => true)) ?>
