<?php
    // Seitentitel
    $this->headTitle()
        ->append("Danke!");

    $this->headStyle()->appendStyle(
        "#bg {
            background-image: url('{$this->imagePath}');
        }");

    $this->headScript()->appendScript(sprintf("
            var isLoggedin = %s;
            var prevNextHandler;",
            $this->isLoggedin ? 'true' : 'false'))
        ->appendFile('/js/pixelfornature.js')
        ->appendFile("/js/danke.js");
?>

<!-- Hintergrundbild -->
<div id="bg" class=""></div>

<?php 
    // Hauptmenue
    echo $this->partial('menu.phtml', array(
        'slides' => array(
            $this->partial('menuThankYou.phtml', array(
                'squarePixels' => $this->squarePixels,
                'isLoggedin' => $this->isLoggedin,
                'loginForm' => $this->loginForm)),
            $this->partial('menuNewMember.phtml', array(
                'newMemberForm' => $this->newMemberForm)),
            $this->partial('menuResetPassword.phtml', array(
                'requestResetForm' => $this->requestResetForm))
        )
    ));
?>

<?php 
    // Kontrollelement
    // echo $this->partial('cameraControl.phtml') ?>
