<?php
// Seitentitel
$this->headTitle()
    ->append("Spende Deine Fläche!");

// CSS
$this->headStyle()->appendStyle(sprintf("
    div#clipping {
        width: %dpx;
        height: %dpx;
    }", 
    $this->dimensions["facebook"]["cover"]["width"], 
    $this->dimensions["facebook"]["cover"]["height"]));
$this->headStyle()->appendStyle(sprintf("
    div#bg0 {
        background-image: url('%s');
    }", 
    $this->imagePath));


// JavaScript JQuery

$this->headScript()
    ->appendFile("/js/vorschau.js");

?>

<div id="overlay" class="fullScreen transparentLight">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <button id="closeOverlay" type="button" class="close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <h1 class="text-center">Schritt 3 von 3</h1>
                <h2 class="text-center">Spende deine Fläche</h2>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div id="clipping">
                    <img src="<?php echo $this->generatedPath; ?>">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4 col-sm-offset-2">
                <button id="upload" type="button" class="btn btn-primary center-block">Mit Facebook verbinden</button>
                <p class="text-center">Du kannst dich im nächsten Schritt mit deinem Facebook-Account anmelden und das Bild automatisch hochladen lassen. Das war‘s schon!</p>
            </div>
            <div class="col-sm-4">
                <a id="download" href="<?php echo $this->generatedPath; ?>" download="PixelForNature.png"
                class="btn btn-default center-block" role="button">Downloaden</a>
                <p class="text-center">Oder du kannst das Bild auf deinen Computer downloaden und manuell bei Facebook hochladen.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <div id="commError" class="alert alert-danger initiallyHidden" role="alert">
                    <p><span class="glyphicon glyphicon-warning-sign"></span>&nbsp;<strong>Kommikationsfehler:</strong><br />Leider lief bei der Kommunikation mit dem Naturefund-Server etwas schief und das Bild konnte nicht hochgeladen werden.</p>
                </div>
                <div id="facebookError" class="alert alert-danger initiallyHidden" role="alert">
                    <p><span class="glyphicon glyphicon-warning-sign"></span>&nbsp;<strong>Fehler</strong>&nbsp;(<span id="errorCode"></span>):<br />Leider lief bei der Kommunikation mit dem Facebook-Server etwas schief und das Bild konnte nicht hochgeladen werden. Vielleicht probierst du es einfach später noch einmal.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="content"></div>