<div id="controllerDiv" class="center-block<?php echo ($this->imageSelectable) ? ' imageSelectable' : ''; ?>">
    <img id="controllerImg" usemap="#controllMap" draggable="false" alt="Bedienelement einer Kamera" 
        src="/images/img_trans.gif" />
    <map name="controllMap">
        <area id="backCtrl" alt="Zurück"
            <?php if ($this->imageSelectable) {?>
                title="Vorheriges Bild" href="javascript:void(0);"
            <?php } ?>
            shape="poly" coords="30,30,70,70,57,101,70,131,30,174,0,101,30,30">
        <area id="forwardCtrl" alt="Vorwärts"
            <?php if ($this->imageSelectable) {?>
                 title="Nächstes Bild" href="javascript:void(0);"
            <?php } ?>
            shape="poly" coords="172,172,132,132,146,101,132,70,172,30,202,101,172,172">
        <area id="flashCtrl" alt="Blitz" title="Hilfe" href="javascript:void(0);"
            shape="poly" coords="30,30,70,70,101,55,132,70,172,30,101,0,30,30">
        <area id="infoCtrl" alt="Info" title="Menü" href="javascript:void(0);"
             shape="poly" coords="132,132,172,172,101,202,30,174,70,131,101,145,132,132">
        <area id="selectCtrl" alt="Auslöser" title="Auslöser" href="javascript:void(0);"
             shape="circle" coords="101,101,42">
    </map>
</div>
