<li>
    <div id="menuResetPassword" class="container-fluid slidingHorizontal">
        <div id="" class="row">
            <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
                <form id="resetPassword" role="form">
                    <h2>Dein Passwort zurücksetzen</h2>
                    <div id="emailResetPasswordGroup" class="form-group">
                        <?php echo $this->resetPasswordForm->email->renderViewHelper(); ?>
                    </div>
                    <button type="submit" class="btn btn-default btn-block">Zurücksetzen</button>
                </form>
            </div>
        </div>
    </div>
</li>
