<?php // Container fuer das Hauptmenue ?>
<div id="menu" class="transparentDark fullscreenOverlay">
    <div class="close-container">
        <button id="closeMenu" type="button" class="close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
    </div>
    <div class="sliding-frame">
        <?php
        echo $this->partial('menuLanding.phtml', array(
            'user' => $this->user,
            'isLoggedin' => $this->isLoggedin,
            'loginForm' => $this->loginForm)); 
        echo $this->partial('menuNewMember.phtml', array('newMemberForm' => $this->newMemberForm));
        echo $this->partial('menuResetPassword.phtml', array('requestResetForm' => $this->requestResetForm));
        echo $this->partial('menuAccount.phtml', array(
            'user' => $this->user,
            'updateMemberForm' => $this->updateMemberForm));
        ?>
    </div>
</div>
