<div id="menuAccount" class="sliding-card slided-left">
    <div class="container-fluid">
        <div id="" class="row">
            <div class="col-sm-12 col-md-4 col-lg-3">
                <h5>Deine Naturefund-Erfolge
                    <hr />
                </h5>

                <h2>Deine bisher gespendeten Pixel</h2>
                <div class="pixelCount">
                    <span id="userPixelsTotal"><?php
                    if ($this->user) {
                        echo number_format($this->user['pixelsTotal'], 0, ',', '.');
                    } ?></span>&nbsp;px&sup2;
                </div>
                <hr />
            </div>
            <div class="col-sm-12 col-md-4 col-lg-6">
                <h5>Deine Aktivitäten
                    <hr class="mainColumn" />
                </h5>
                <h1><strong>Hallo <span class="username"><?php echo $this->user['vorname'] ?></span></strong>, das hast du bereits mit Naturefund erreicht:</h1>
                <ul id="timeline" class="member-activities non-decorated">
                    <?php 
                    if (!$this->user) {
                        $this->user = array(
                            'timeline' => array());
                    }
                    // add one empty entry at the beginning to create a hidden template that JS can use in an ajax call
                    $hiddenTemplate = array(0 => array());
                    $this->user['timeline'] = array_merge($hiddenTemplate, $this->user['timeline']);

                    foreach ($this->user['timeline'] as $index => $entry) {
                        $hidden = ($index != 0) ? '' : 'hidden';
                        $dateFormatted = !$hidden ? $entry['datum_erstellt'] : '';
                        if ($hidden || $entry['type'] == 'signup') {
                    ?>
                    <li class="signup <?php echo $hidden; ?>">
                        <p>Du bist am <strong class="dateSignup"><?php echo $dateFormatted; ?></strong> Weltretter bei Naturefund geworden.</p>
                    </li>
                    <?php
                        }
                        if ($hidden || $entry['type'] == 'pixelspende') {
                            $pixelsFormatted = !$hidden ? number_format($entry['pixel_gespendet'], 0, ',', '.') : '';
                            $projectName = !$hidden ? $entry['timeline_name'] : '';
                    ?>
                    <li class="donation <?php echo $hidden; ?>">
                        <p>Am <strong class="dateDonated"><?php echo $dateFormatted; ?></strong> hast du <strong><span class="pixelsDonated"><?php echo $pixelsFormatted; ?></span> px&sup2;</strong> für <span class="projectDonated"><?php echo $projectName; ?></span> gespendet.</p>
                    </li>
                        <?php
                        }
                    }
                    ?>
                </ul>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-3">
                <h5>Konto Einstellungen
                    <hr />
                </h5>
                <form id="updateMember" class="" role="form">
                    <h2>Ihre persönlichen Angaben</h2>
                    <div id="combiNames" class="combi-input-container">
                        <?php 
                        $this->updateMemberForm->vorname->class .= ' combi-input-50L';
                        echo $this->updateMemberForm->vorname->renderViewHelper();
                        $this->updateMemberForm->nachname->class .= ' combi-input-50R';
                        echo $this->updateMemberForm->nachname->renderViewHelper();
                        ?>
                    </div>
                    <div id="strasseUpdateGroup" class="form-group">
                        <?php echo $this->updateMemberForm->strasse->renderViewHelper() ?>
                    </div>
                    <div id="combiPlzOrt" class="combi-input-container">
                        <?php 
                        $this->updateMemberForm->plz->class .= ' combi-input-50L';
                        echo $this->updateMemberForm->plz->renderViewHelper();
                        $this->updateMemberForm->ort->class .= ' combi-input-50R';
                        echo $this->updateMemberForm->ort->renderViewHelper();
                        ?>
                    </div>
                    <div id="telefonUpdateGroup" class="form-group">
                        <?php echo $this->updateMemberForm->telefon->renderViewHelper() ?>
                    </div>

                    <h2>Ihre Zugangsdaten</h2>
                    <div id="emailUpdateGroup" class="form-group">
                        <?php echo $this->updateMemberForm->email->renderViewHelper() ?>
                    </div>
                    <div id="combiPassword" class="combi-input-container">
                        <?php
                        $this->updateMemberForm->passwort->class .= ' combi-input-50L';
                        echo $this->updateMemberForm->passwort->renderViewHelper();
                        $this->updateMemberForm->passwortWiederholt->class .= ' combi-input-50R';
                        echo $this->updateMemberForm->passwortWiederholt->renderViewHelper();
                        ?>
                    </div>
                    <div class="float-container">
                        <button type="submit" class="btn btn-default pull-right">Aktualisieren</button>
                    </div>
                </form>
                <div class="float-container">
                    <a id="deleteAccount" class="pull-right">Möchtest du dein Konto löschen?</a>
                </div>
            </div>
        </div>
    </div>
</div>
