<body>
<p>
Hallo <?php echo $this->vorname ?>,
<br/>
Vielen Dank für Ihre Anmeldung bei Naturefund.de!
<br/>
Ihr Benutzerkonto wurde angelegt. Bitte bestätigen Sie Ihren Zugang durch klicken des folgend Links:
<br/>
Anmeldung bei NatureFund <a href="<?php echo $this->url ?>" >bestätigen</a>.
<br/>
Oder kopieren Sie folgende URL in die Adresszeile Ihres Browsers:
<br/>
<?php echo $this->url ?>
<br/>
Wir freuen uns auf Ihren Besuch.
</p>
</body>
