<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head><body bgcolor="#FFFFFF" text="#000000"><i
>Hallo <?php echo $this->vorname ?>,</i><br
/><div style="margin-top:2em"><p><br
/>jemand hat um das <b>Zurücksetzen deines Passworts</b> bei <a href="http://pixelfornature.org"
>Pixel for nature</a> gebeten. Wenn du dies tun möchtest, dann klicke auf den folgend Link oder kopiere die nachfolgende URL in die Adressleiste deines Browsers:<br
/></p><p
>Dein Passwort jetzt <a href="<?php echo $this->url ?>"
>zurücksetzen</a>.</p
><a href="<?php echo $this->url ?>"><?php echo $this->url ?></a><br
/><br
/><p><i>Vielen Dank!</i></p><br/
></div></body></html>