<?php $this->headTitle()->append('Passwort zurücksetzen'); ?>

<div id="overlayReset" class="transparentDark fullscreenOverlay">
    <div class="close-container">
        <button id="closeReset" type="button" class="close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
    </div>
	<div id="" class="container">
	    <div id="" class="row">
            <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            	<?php if ($this->errors) { ?>
            		<h1>Fehler!</h1>
            		<p>Bitte klick erneut auf 'Passwort vergessen' und lass dir eine neue E-Mail schicken</p>
            		<a href="/" class="btn btn-default btn-block">Zurück</a>

            	<?php } else { ?>
				<form id="resetPassword" role="form">
	                <h2>Dein Passwort zurücksetzen</h2>
					<div id="emailResetGroup" class="form-group">
						<?php echo $this->resetPasswordForm->email->renderViewHelper(); ?>
					</div>
	                <div id="combiPassword" class="combi-input-container">
	                    <?php
	                    $this->resetPasswordForm->passwort->class .= ' combi-input-50L';
	                    echo $this->resetPasswordForm->passwort->renderViewHelper();
	                    $this->resetPasswordForm->passwortWiederholt->class .= ' combi-input-50R';
	                    echo $this->resetPasswordForm->passwortWiederholt->renderViewHelper();
	                    ?>
	                </div>
	                <input id="verifizierungHashResetPassword" type="hidden" value="<?php echo $this->hash ?>" />
	                <div class="float-container">
	                    <button type="submit" class="btn btn-default btn-block">Aktualisieren</button>
	                </div>
				</form>
				<?php } ?>
			</div>
		</div>
	</div>
</div>