<?php $this->headTitle()->append('Passwort zurücksetzen'); ?>

<div id="" class="container-fluid transparentDark">
    <div id="" class="row">
        <div class="col-sm-4 col-sm-offset-4">
			<form id="" role="form">
				<div id="emailResetGroup" class="form-group">
					<?php echo $this->resetPasswordForm->email->renderViewHelper() ?>
				</div>
				<div id="passwortResetGroup" class="form-group">
					<?php echo $this->resetPasswordForm->passwort->renderViewHelper() ?>
				</div>
				<div id="passwortWiederholtResetGroup" class="form-group">
					<?php echo $this->resetPasswordForm->passwortWiederholt->renderViewHelper() ?>
				</div>
			</form>
		</div>
	</div>
</div>