#!/bin/sh
#
# Loescht (-delete) alle Dateien (type f) im angegebenen 
# Verzeichnis (min/maxdepth 1) die aelter als ein Tag (mtime +1) sind.

find /var/www/vhosts/pixelfornature.org/httpdocs/public/images/tmp -mindepth 1 -maxdepth 1 -type f -mtime +1 -delete
