<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de" manifest="http://pixelfornature.local/pixelfornature.appcache">
<head>
    <?php echo $this->headTitle(); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headMeta(); ?>

    <link rel="prefetch" href="/images/socials-icon.png" />
    <link rel="prefetch" href="/images/ausloeserMap.png" />
    <link rel="prefetch" href="/images/projekt.jpg" />
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle() ?>
    <link rel="stylesheet" href="/css/pixelfornature.css">

    <?php echo $this->headScript(); ?>
</head>

<body>
    <?php echo $this->layout()->content; ?>
</body>

</html>
