<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de" 
>
<!-- manifest="http://pixelfornature.local/pixelfornature.appcache">
 -->
<head>
    <?php echo $this->headTitle(); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headMeta(); ?>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/pixelfornature.css">
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle() ?>

    <!-- JQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="/js/pixelfornature.js"></script>
    <?php
    if (isset($this->session) && $this->session->loadMenu) {
        $this->session->loadMenu = false;
        $this->headScript()->appendScript(
            "$(function() {
                $('div#menu').css({top: 0});
            })");
    } ?>
    <?php echo $this->headScript(); ?>
</head>

<body>
    <!--     <div id=mitglied> -->
    <?php //echo $this->eingeloggtAls(); ?>
    <!--     </div> -->
    <div id="bgWrapper">
        <div id="bg0" class="bg<?php echo ($this->step == 2) ? ' blur' : ''; ?>"></div>
        <div id="bg1" class="bg<?php //echo ($this->step == 3) ? ' transparentLight' : ''; ?>"></div>
    </div>

    <ul class="hidden">
        <li>
            <div id="menuLanding" class="container-fluid slidingHorizontal">
                <div id="" class="row">
                    <div class="col-sm-3">
                        Die Kampagne
                        <hr />

                        <h3>Bisher gespendete Pixel</h3>
                        <div class="pixelCount">
                            <?php echo number_format($this->session->project['pixelsTotal'], 0, ',', '.'); ?>&nbsp;px&sup2;
                        </div>
                        <hr />

                        <h3>Die letzten Pixelspender</h3>
                        <ul>
                            <?php
                            $donorWithCityFormat = '<li><p>%s %s aus %s</p></li>';
                            $donorWithoutCityFormat = '<li><p>%s %s</p></li>';
                            foreach ($this->session->project['lastDonors'] as $donor) {
                                if (isset($donor['ort'])) {
                                    echo sprintf($donorWithCityFormat, $donor['vorname'], $donor['nachname'], $donor['ort']);
                                } else {
                                    echo sprintf($donorWithoutCityFormat, $donor['vorname'], $donor['nachname']);
                                }
                            } ?>
                        </ul>
                        <hr />

                        <h3>Pixel für Natur</h3>
                        <p>Du kannst jetzt auch digitale Fläche spenden, ganz
                        umsonst und mit großer Wirkung für die Natur! Das Prinzip
                        ist ganz einfach: Du suchst dir nach Belieben ein Bild aus
                        und verwendest es bei Facebook als Titelbild.</p>
                        <button type="button" class="btn btn-default">Mehr erfahren</button>
                    </div>
                    <div class="col-sm-6">
                        Aktuelles Projekt
                        <hr class="mainColumn" />

                        <h3><?php echo $this->session->project['name']; ?></h3>
                        <?php echo $this->session->project['beschreibung']; ?>
                        <button type="button" class="btn btn-default">Jetzt spenden</button>
                    </div>
                    <div class="col-sm-3">
                        Das Unternehmen
                        <hr />

                        <h3>Über Naturefund</h3>
                        <p>Wir setzen uns für den Naturschutz ein. Wir kaufen
                        Land für Natur, um Lebensraum für die Artenvielfalt zu
                        bewahren. Auch im Klimaschutz sind wir aktiv, wobei wir
                        vor allem Wälder schützen und Bäume pflanzen.<p>
                        <button type="button" class="btn btn-default">Mehr erfahren</button>
                        <hr />

                        <h3>Mein Naturefund Account</h3>
                        <?php 
                        if ($this->isLoggedin) {?>
                        <button id="memberAccount" type="button" class="btn btn-default">Mein Account</button>
                        <button id="logoutMember" type="button" class="btn btn-default">Logout</button>
                        <?php } else {?>
                        <p>Um deine Pixel zu sammeln, melde dich einfach mit
                        deinem persönlichen Naturefund-Account an:</p>
                        <div class="form-inline" role="form">
                            <div id="emailLoginGroup" class="form-group">
                                <?php echo $this->loginForm->email->renderViewHelper(); ?>
                            </div>
                            <div id="passwortLoginGroup" class="form-group">
                                <?php echo $this->loginForm->passwort->renderViewHelper(); ?>
                            </div>
                            <button id="loginMember"><span class="glyphicon glyphicon-chevron-right"></span></button>
                            <div id="loginFailed" class="form-group">
                            </div>
                        </div>
                        <a class="registerNow">Noch nicht registriert? Jetzt mitmachen!</a><br />
                        <a class="lostPassword">Passwort vergessen?</a>
                        <?php } ?>
                        <hr />

                        <h3>Newsletter</h3>
                        <p>Möchtest du immer auf dem neusten Stand bleiben? Dann
                        abboniere jetzt den Naturefund-Newsletter:</p>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="E-Mail">
                            <span class="input-group-addon glyphicon glyphicon-chevron-right"></span>
                        </div>
                    </div>
                </div>
            </div>
        </li>
        <?php if (!$this->isLoggedin) {?>
        <li>
            <div id="menuNewMember" class="container-fluid slidingHorizontal">
                <div id="" class="row">
                    <div class="col-sm-4 col-sm-offset-4">
                        <h2>Einen neuen Naturefund Account erstellen</h2>
                        <div id="vornameSignupGroup" class="form-group">
                            <?php echo $this->newMemberForm->vorname->renderViewHelper() ?>
                        </div>
                        <div id="nachnameSignupGroup" class="form-group">
                            <?php echo $this->newMemberForm->nachname->renderViewHelper() ?>
                        </div>
                        <div id="emailSignupGroup" class="form-group">
                            <?php echo $this->newMemberForm->email->renderViewHelper() ?>
                        </div>
                        <div id="passwortSignupGroup" class="form-group">
                            <?php echo $this->newMemberForm->passwort->renderViewHelper() ?>
                        </div>
                        <div id="passwortWiederholtSignupGroup" class="form-group">
                            <?php echo $this->newMemberForm->passwortWiederholt->renderViewHelper() ?>
                        </div>
                        <button id="registerNewMember" type="button" class="btn btn-default btn-block">Registrieren</button>
                    </div>
                </div>
            </div>
        </li>
        <?php } else {?>
        <li>
            <div id="menuResetPassword" class="container-fluid slidingHorizontal">
                <div id="" class="row">
                    <div class="col-sm-4 col-sm-offset-4">
                        <h2>Dein Passwort zurücksetzen</h2>
                        <input type="text" placeholder="E-Mail" />
                        <button type="btn btn-default">Zurücksetzen</button>
                    </div>
                </div>
            </div>
        </li>
        <li>
            <div id="menuAccount" class="container-fluid slidingHorizontal">
                <div id="" class="row">
                    <div class="col-sm-3">
                        Deine Naturefund-Erfolge
                        <hr />

                        <h3>Deine bisher gespendeten Pixel</h3>
                        <div class="pixelCount">
                            <?php echo number_format($this->session->user['pixelsTotal'], 0, ',', '.') ?>&nbsp;px&sup2;
                        </div>
                        <hr />
                    </div>
                    <div class="col-sm-6">
                        Deine Aktivitäten
                        <hr class="mainColumn" />
                        <h2><strong>Hallo <?php echo $this->session->user['vorname'] ?></strong>, das hast du bereits mit Naturefund erreicht:</h2>
                        <ul>
                            <?php 
                            $signupFormat = '<li><p>Du bist am <strong>%s</strong> Weltretter bei Naturefund geworden.</p></li>';
                            $spendeFormat = '<li><p>Am <strong>%s</strong> hast du <strong>%s px&sup2;</strong> für %s gespendet.</p></li>';
                            date_default_timezone_set('Europe/Berlin');  
                            setlocale(LC_ALL, "de_DE", "de_DE@euro", "deu", "deu_deu", "german");
                            
                            foreach ($this->session->user['timeline'] as $entry) {
                                $dateFormatted = strftime('%d. %B %Y', strtotime($entry['datum_erstellt']));
                                if ($entry['type'] == 'signup') {
                                    echo sprintf($signupFormat, $dateFormatted);
                                }
                                if ($entry['type'] == 'pixelspende') {
                                    echo sprintf($spendeFormat, $dateFormatted, number_format($entry['pixel_gespendet'], 0, ',', '.'), $entry['timeline_name']);
                                }
                            }
                            ?>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        Konto Einstellungen
                        <hr />
                        <h3>Ihre Angaben</h3>
                        <em>Ihr Name</em>
                        <div class="form-inline" role="form">
                            <div id="vornameUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->vorname->renderViewHelper() ?>
                            </div>
                            <div id="nachnameUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->nachname->renderViewHelper() ?>
                            </div>
                        </div>
                        <em>Ihre Kontaktdaten</em>
                        <div class="form-inline" role="form">
                            <div id="strasseUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->strasse->renderViewHelper() ?>
                            </div>
                            <div id="plzUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->plz->renderViewHelper() ?>
                            </div>
                            <div id="ortUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->ort->renderViewHelper() ?>
                            </div>
                            <div id="telefonUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->telefon->renderViewHelper() ?>
                            </div>
                            <button id="updateContact" type="button" class="btn btn-default">Aktualisieren</button>
                        </div>
                        <h3>Ihre Zugangsdaten</h3>
                        <div class="form-inline" role="form">
                            <div id="emailUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->email->renderViewHelper() ?>
                            </div>
                            <div id="passwortUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->passwort->renderViewHelper() ?>
                            </div>
                            <div id="passwortWiederholtUpdateGroup" class="form-group">
                                <?php echo $this->updateMemberForm->passwortWiederholt->renderViewHelper() ?>
                            </div>
                            <button id="updateCredential" type="button" class="btn btn-default">Aktualisieren</button>
                        </div>
                        <a href="">Möchten Sie Ihr Konto löschen?</a>
                    </div>
                </div>
            </div>
        </li>
        <?php } ?>
        <li>
            <div id="menuThankyou" class="container slidingHorizontal">
                <div class="row">
                    <div class="col-sm-4 col-sm-offset-4">
                        <h2>Du hast erfolgreich</h2>
                        <div class="pixelCount">
                            <?php echo $this->squarePixels ?> px&sup2;
                        </div>
                        <h2>gespendet.</h2>
                        <hr />
                        <p>Um deine Pixel zu sammeln, melde dich einfach mit deinem persönlichen Naturefund-Account an:</p>
                        <form>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="E-Mail">
                                <input type="text" class="form-control" placeholder="Passwort">
                                <span class="input-group-addon glyphicon glyphicon-chevron-right"></span>
                            </div>
                            <a class="registerNow">Noch nicht registriert? Jetzt mitmachen!</a><br />
                            <a class="lostPassword">Passwort vergessen?</a>
                        </form>
                    </div>
                </div>
            </div>
        </li>
    </ul>

    <div id="menu" class="transparentDark fullscreenOverlay">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <button id="closeMenu" type="button" class="close">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                </div>
            </div>
        </div>
        <div id="slidingFrame">
            <div id="slidingContainer">
            </div>
        </div>
    </div>

    <?php echo $this->layout()->content; ?>

    <div>
        <div id="controllerDiv" class="center-block<?php echo ($this->step == 1) ? ' imageSelectable' : ''; ?>">
            <img id="controllerImg" usemap="#controllMap" draggable="false" alt="Bedienelement einer Kamera" 
                src="/images/img_trans.gif"></img>
            <map name="controllMap">
                <area id="backCtrl" alt="Zurück"
                    <?php if ($this->step == 1) {?>
                        title="Vorheriges Bild" href="javascript:void(0);"
                    <?php } ?>
                    shape="poly" coords="30,30,70,70,57,101,70,131,30,174,0,101,30,30">
                <area id="forwardCtrl" alt="Vorwärts"
                    <?php if ($this->step == 1) {?>
                         title="Nächstes Bild" href="javascript:void(0);"
                    <?php } ?>
                    shape="poly" coords="172,172,132,132,146,101,132,70,172,30,202,101,172,172">
                <area id="flashCtrl" alt="Blitz" title="Hilfe" href="javascript:void(0);"
                    shape="poly" coords="30,30,70,70,101,55,132,70,172,30,101,0,30,30">
                <area id="infoCtrl" alt="Info" title="Menü" href="javascript:void(0);"
                     shape="poly" coords="132,132,172,172,101,202,30,174,70,131,101,145,132,132">
                <area id="selectCtrl" alt="Auslöser" title="Auslöser" href="javascript:void(0);"
                     shape="circle" coords="101,101,42">
            </map>
        </div>
        <?php if ($this->step == 2) { ?>
        <div id="rotationSliderContainer" class="">
            <div id="rotationSlider"></div>
        </div>
        <?php } ?>
    </div>

</body>

</html>
