<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de" 
>
<!-- manifest="http://pixelfornature.local/pixelfornature.appcache">
 -->
<head>
    <?php echo $this->headTitle(); ?>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headMeta(); ?>

    <link rel="stylesheet" href="/css/pixelfornature.css">
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle() ?>

    <!-- JQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="/js/pixelfornature.js"></script>
    <?php
    if (isset($this->session) && $this->session->loadMenu) {
        $this->session->loadMenu = false;
        $this->headScript()->appendScript(
            "$(function() {
                $('div#menu').css({top: 0});
            })");
    } ?>
    <?php echo $this->headScript(); ?>
</head>

<body>
    <?php echo $this->layout()->content; ?>

    <div>
        <div id="controllerDiv" class="center-block<?php echo ($this->step == 1) ? ' imageSelectable' : ''; ?>">
            <img id="controllerImg" usemap="#controllMap" draggable="false" alt="Bedienelement einer Kamera" 
                src="/images/img_trans.gif"></img>
            <map name="controllMap">
                <area id="backCtrl" alt="Zurück"
                    <?php if ($this->step == 1) {?>
                        title="Vorheriges Bild" href="javascript:void(0);"
                    <?php } ?>
                    shape="poly" coords="30,30,70,70,57,101,70,131,30,174,0,101,30,30">
                <area id="forwardCtrl" alt="Vorwärts"
                    <?php if ($this->step == 1) {?>
                         title="Nächstes Bild" href="javascript:void(0);"
                    <?php } ?>
                    shape="poly" coords="172,172,132,132,146,101,132,70,172,30,202,101,172,172">
                <area id="flashCtrl" alt="Blitz" title="Hilfe" href="javascript:void(0);"
                    shape="poly" coords="30,30,70,70,101,55,132,70,172,30,101,0,30,30">
                <area id="infoCtrl" alt="Info" title="Menü" href="javascript:void(0);"
                     shape="poly" coords="132,132,172,172,101,202,30,174,70,131,101,145,132,132">
                <area id="selectCtrl" alt="Auslöser" title="Auslöser" href="javascript:void(0);"
                     shape="circle" coords="101,101,42">
            </map>
        </div>
        <?php if ($this->step == 2) { ?>
        <div id="rotationSliderContainer" class="">
            <div id="rotationSlider"></div>
        </div>
        <?php } ?>
    </div>

</body>

</html>
