<?php
// Seitentitel
$this->headTitle()
    ->append("2. Wähle einen Ausschnitt");

$this->headStyle()->appendStyle(sprintf("
    div#clipping {
        width: %dpx;
        height: %dpx;
    }", 
    $this->dimensions["facebook"]["cover"]["width"], 
    $this->dimensions["facebook"]["cover"]["height"]));

// JavaScript
$this->headScript()
    ->appendFile("/js/jquery/jquery.panzoom-1.7.0.js");
$this->headScript()
    ->appendFile("/js/purl/purl.js");
$this->headScript()
    ->appendFile("/js/circleSlider/circleSlider.js");
$this->headScript()
    ->appendScript(sprintf("
	var original = {
		width : %d,
		height : %d,
        ratio : %f
	};

	// Bilddimensionen der Facebook Coverfotos
	var fbCover = {
		width : %d,
		height : %d,
		minScale : %f,
		maxScale : 1,
	};

    var imagePath = '%s'",
    $this->dimensions ["original"] ["width"], 
    $this->dimensions ["original"] ["height"], 
    $this->dimensions ["original"] ["width"] / $this->dimensions ["original"] ["height"], 
    $this->dimensions ["facebook"] ["cover"] ["width"],
    $this->dimensions ["facebook"] ["cover"] ["height"], 
    $this->dimensions ["facebook"] ["cover"] ["width"] / $this->dimensions ["original"] ["width"],
    $this->imagePath));
$this->headScript()
    ->appendFile("/js/ausschnitt.js");

$htmlEntities = new Zend_Filter_HtmlEntities();
?>


<div class="absoluteWrapper" >
    <div id="helpBox" class="container transparentLight">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <button id="closeHelp" type="button" class="close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <h1>Schritt 2 von 3</h1>
                <h2>Personalisiere deine Fläche</h2>
            </div>
            <div class="row">
                <div class="col-sm-1 col-sm-offset-1">
                    <img src="/images/hilfe1-1.png"/ class="center-block">
                    <p>Mit den Pfeiltasten kannst du die Bilder durchstöbern.</p>
                </div>
                <div class="col-sm-1">
                    <div class="center-block">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </div>
                </div>
                <div class="col-sm-1">
                    <img src="/images/hilfe1-1.png"/ class="center-block">
                    <p>Mit dem Drehknopf kannst du rein- und rauszoomen.</p>
                </div>
                <div class="col-sm-1">
                    <div class="center-block">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </div>
                </div>
                <div class="col-sm-1">
                    <img src="/images/hilfe1-1.png"/ class="center-block">
                    <p>Mit geklickter Maustaste kannst du in der Fläche den Ausschnitt wählen.</p>
                </div>
                <div class="col-sm-1">
                    <div class="center-block">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </div>
                </div>
                <div class="col-sm-1">
                    <img src="/images/hilfe1-1.png"/ class="center-block">
                    <p>In dem Textfeld kannst du deinen Namen eintragen.</p>
                </div>
                <div class="col-sm-1">
                    <div class="center-block">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </div>
                </div>
                <div class="col-sm-1">
                    <img src="/images/hilfe1-2.png" class="center-block" />
                    <p>Mit dem Auslöser bestätigst du deine Auswahl.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="logo">
    <img id="Naturefundlogo" alt="Naturefund-Logo" src="/images/Naturefund Logo.png" />
</div>

<div id="content" class="container">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div id="clipping" class="shadowed center-block">
                <img id="clippingImage" src="<?php echo $htmlEntities->filter($this->imagePath); ?>" />
                <form id="ausschnitt" action="vorschau" method="get">
                    <input type="text" id="name" name="name" maxlength="25" placeholder="Dein Name"/>
                    <input type="hidden" id="x" name="x" value="0" />
                    <input type="hidden" id="y" name="y" value="0" />
                    <input type="hidden" id="scale" name="scale" value="0" />
                    <input type="hidden" id="image" name="image"
                        value="<?php echo $htmlEntities->filter($this->params["image"]); ?>"
                    />
                </form>
                <img id="profilePhotoOverlay" src="/images/fbHead.png" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <div id="illegalNameMsg" class="initiallyHidden ui-widget-content ui-corner-all">
                <h3 id="illegalNameHeader" class="ui-widget-header ui-corner-all">Name nicht erlaubt</h3>
                <p>Bitte vermeiden Sie die folgenden Worte in Ihren Namen:</p>
                <p id="illegalWords"></p>
            </div>
        </div>
    </div>
</div>