<?php
// Seitentitel
$this->headTitle()
    ->append("1. Wähle ein Bild");

// JavaScript
$this->headScript()
    ->appendFile("/js/purl/purl.js");

$this->headScript()
    ->appendScript("var imageUrls = " . $this->galeryFilesJs . ";");
$this->headScript()
    ->appendFile("/js/auswahl.js");
?>


<div class="absoluteWrapper" >
    <div id="helpBox" class="container transparentLight">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <button id="closeHelp" type="button" class="close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
            </div>
        </div>
        <div id="helpContent" class="row">
            <div class="col-sm-12">
                <h1>Schritt 1 von 3</h1>
                <h2>Durchstöbere die Bilder</h2>
            </div>
            <div class="row">
                <div class="col-sm-3 col-sm-offset-2 col-md-2 col-md-offset-3">
                    <img src="/images/hilfe1-1.png"/ class="center-block">
                    <p>Mit den Pfeiltasten kannst du die Bilder durchstöbern.</p>
                </div>
                <div class="col-sm-2">
                    <span class="glyphicon glyphicon-chevron-right center-block"></span>
                </div>
                <div class="col-sm-3 col-md-2">
                    <img src="/images/hilfe1-2.png" class="center-block" />
                    <p>Mit dem Auslöser bestätigst du deine Auswahl.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<form id="auswahl" action="ausschnitt" method="get">
    <input type="hidden" id="image" name="image" value="" />
</form>

<div id="content"></div>