<?php
// Seitentitel
$this->headTitle()
    ->prepend("Fläche für Natur");

// CSS
$this->headLink()
    ->appendStylesheet("/css/flaeche-fuer-natur.css");
$this->headLink()
    ->appendStylesheet("/css/skins/smoothness/jquery-ui-1.10.3.custom.min.css");

// JavaScript JQuery
$this->headScript()
    ->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js");
$this->headScript()
    ->appendFile("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js");
?>

<div id="" class="container">
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 lightboxDark">
		    <div class="row">
		        <div class="col-sm-12">
		            <span id="closeMenu" class="glyphicon glyphicon-remove clickable"></span>
		        </div>
		    </div>
		    <div class="row">
		        <div class="col-sm-12">
		        	<h2>Du hast erfolgreich</h2>
		            <div class="pixelCount">
		                <?php echo $this->squarePixels ?> px&sup2;
		            </div>
		            <h2>gespendet.</h2>
		            <hr />
		            <p>Um deine Pixel zu sammeln, melde dich einfach mit deinem persönlichen Naturefund-Account an:</p>
		            <form>
		   	            <div class="input-group">
			                <input type="text" class="form-control" placeholder="E-Mail">
			                <input type="text" class="form-control" placeholder="Passwort">
			                <span class="input-group-addon glyphicon glyphicon-chevron-right"></span>
			            </div>
			            <a>Noch nicht registriert? Jetzt mitmachen!</a><br />
			            <a>Passwort vergessen?</a>

		            </form>
		        </div>
		    </div>

        </div>
    </div>
</div>
