<?php
// Seitentitel
$this->headTitle()
    ->prepend("Fläche für Natur");

// CSS
$this->headLink()
    ->appendStylesheet("/css/flaeche-fuer-natur.css");
$this->headLink()
    ->appendStylesheet("/css/skins/smoothness/jquery-ui-1.10.3.custom.min.css");

// JavaScript JQuery
$this->headScript()
    ->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js");
$this->headScript()
    ->appendFile("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js");
?>
Introvideo?