<?php
// Seitentitel
$this->headTitle()
    ->prepend("Vorschau");

// CSS
$this->headLink()
    ->appendStylesheet("/css/flaeche-fuer-natur.css");
$this->headLink()
    ->appendStylesheet("/css/skins/smoothness/jquery-ui-1.10.3.custom.min.css");

// JavaScript JQuery
$this->headScript()
    ->prependFile("//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js");
$this->headScript()
    ->appendFile("//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js");
$this->headScript()
    ->appendFile("/js/purl/purl.js");
$this->headScript()
    ->appendFile("/js/flaeche-fuer-natur.js");
$this->headScript()
    ->appendFile("/js/vorschau.js");

$htmlEntities = new Zend_Filter_HtmlEntities();
?>
<div id="fb-root"></div>

<div id="main" class="hCentered">
    <div id="clipping" class="shadowed" style="<?php
    echo sprintf("width:%dpx;height:%dpx;", $this->dimensions ["facebook"] ["cover"] ["width"], 
            $this->dimensions ["facebook"] ["cover"] ["height"]);
    ?>">
        <img id="clippingImage" src="/images/galerie/<?php echo $htmlEntities->filter($this->params["image"]); ?>">
        <div id="clippingLabel">
            <div id="labelUserName" class="labelText"></div>
            <div id="labelConst" class="labelText">spendet Fläche für Natur</div>
        </div>
        <div id="logo">
            <img id="Naturefundlogo" alt="Naturefund-Logo" src="/images/Naturefund Logo BG.png">
        </div>
        <div id="profilePhotoOverlay"></div>
    </div>
</div>


<div id="form" class="hCentered">
    <input id="upload" type="button" value="Bild hochladen" />
    <div id="progressbar" class="initiallyHidden" >
        <span class="progressLabel">Lade...</span>
    </div>
    <div id="breadcumbs">
        <?php echo $this->partial("breadcrumbs.phtml", $this->params); ?>
    </div>
    <div id="successMsg" class="initiallyHidden ui-widget infoMsg">
        <div class="ui-state-highlight ui-corner-all">
            <p>
                <span class="ui-icon ui-icon-info"></span> <strong>OK!</strong><br /> Ihr neues
                Cover-Photo wurde erfolgreich zu Ihren Facebook-Photos hinzugefügt und befindet sich
                in einem Fotoalbum mit dem Namen "Naturefund". Bitte besätigen Sie das neue
                Cover-Bild im geöffneten Browserfenster.
            </p>
        </div>
    </div>
    <div id="commError" class="initiallyHidden ui-widget infoMsg">
        <div class="ui-state-error ui-corner-all">
            <p>
                <span class="ui-icon ui-icon-alert"></span> <strong>Kommikationsfehler</strong>:<br />
                Bei der Kommunikation mit dem Naturefund-Server trat ein Fehler auf. Ihr Bild wurde
                nicht hochgeladen!
            </p>
        </div>
    </div>
    <div id="facebookError" class="initiallyHidden ui-widget infoMsg">
        <div class="ui-state-error ui-corner-all">
            <p>
                <span class="ui-icon ui-icon-alert"></span> <strong>Fehler</strong> (<span
                    id="errorCode"
                ></span>):<br /> Bei der Kommunikation mit Facebook trat ein Fehler auf. Ihr Bild
                wurde nicht hochgeladen!<br /> Bitte probieren Sie es zu einem späteren Zeitpunkt
                noch einmal.
            </p>
        </div>
    </div>
</div>

<div id="controls"></div>